jwt:
  secret:
    privateKey: |
      -----BEGIN PRIVATE KEY-----
      DANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7pZp4mUUHAZ0h
      
      -----END PRIVATE KEY-----
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      GGFHVx4hgPW+877dlZW7Z0V62lO4yKOhT4dtxJOoccShfd7JOvcBV
      3QIDAQAB
      -----END PUBLIC KEY-----
